Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

========================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception-1.py =========================================================
please note number cannot divided with zero division by zero
Bye

========================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception-1.py =========================================================
please note number cannot divided with zero
Bye

========================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception-1.py =========================================================
please note number cannot divided with zero division by zero
Bye

========================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception-1.py =========================================================
please note number cannot divided with zero division by zero
Bye

========================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception-1.py =========================================================
please note number cannot divided with zero
Bye

========================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception-1.py =========================================================
please note number cannot divided with zero division by zero
Bye
resource open
don't give second no. as zero division by zero
resource closed

========================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception-2.py =========================================================
resource open
don't give second no. as zero division by zero
resource closed

=========================================================== RESTART: C:/Users/PC/Desktop/crt training/DAY 6 -programs/exception-1.py ===========================================================
please note number cannot divided with zero division by zero
Bye

================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception-3-specific error.py ==================================================
enter a number:20
resopurce open
1.0
resourse closed

================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception-3-specific error.py ==================================================
enter a number:0
respurce open
1.0
resourse closed

================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception-3-specific error.py ==================================================
enter a number:0
resource open
please note number cant be divided by zero
resourse closed

================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception-3-specific error.py ==================================================
enter a number:p
invalid input invalid literal for int() with base 10: 'p'
resourse closed

================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception-3-specific error.py ==================================================
enter a number:   
invalid input invalid literal for int() with base 10: '   '
resourse closed

======================================================= RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception -raise.py =======================================================
101
Traceback (most recent call last):
  File "C:/Users/PC/AppData/Local/Programs/Python/Python310/exception -raise.py", line 3, in <module>
    raise Exception("x should be even number")
Exception: x should be even number
>>> 
======================================================= RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception -raise.py =======================================================
100
x is even number....correct
>>> 
======================================================= RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception -raise.py =======================================================
101
x should be even number
>>> 
======================================================= RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/exception -raise.py =======================================================
101
Traceback (most recent call last):
  File "C:/Users/PC/AppData/Local/Programs/Python/Python310/exception -raise.py", line 3, in <module>
    raise Exception("x should be even number")
Exception: x should be even number
>>> 
=========================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/class-obj.py ==========================================================
YES
YES
>>> 
========================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/constructor.py =========================================================
ID: 18
Name:  virat
ID: 17
Name:  shreyas
>>> 
======================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/class-variables.py =======================================================
class variable inside class 10
10
30
dell 10
YES
Instance access 20
>>> 
======================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/class-variables.py =======================================================
class variable inside class 10
10
30
dell 10
YES
Instance access 20
>>> 
======================================================== RESTART: C:/Users/PC/AppData/Local/Programs/Python/Python310/class-variables.py =======================================================
class variable inside class 1
1
100
dell 1
YES
Instance access 99
